# Jekyll에 오신 것을 환영합니다!
#
# 이 구성 파일은 사이트 전체에 영향을 미치는 설정을 위한 것입니다. 일반적으로 한 번 설정하면 이후에는 거의 수정할 필요가 없습니다.
# 기술적인 이유로, 이 파일은 `jekyll serve`를 사용할 때 자동으로 다시 로드되지 않습니다.
# 이 파일을 변경한 경우 서버 프로세스를 다시 시작하십시오.

# 테마 설정
#
# 테마와 원격 테마 중 무엇을 사용할지 결정하려면 문서를 검토하십시오.
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 사이트 설정
locale                   : "ko-KR"
title                    : "학술용"
title_separator          : "-"
subtitle                 : 학술용 저장소 # 사이트 제목 아래에 나타나는 사이트 태그라인
name                     : "당신의 이름"
description              : "놀라운 웹사이트."
url                      : # 사이트의 기본 호스트 이름 및 프로토콜 예: "https://mmistakes.github.io"
baseurl                  : # 사이트의 하위 경로 예: "/blog"
repository               : # GitHub 사용자 이름/레포지토리 이름 예: "mmistakes/minimal-mistakes"
teaser                   : "/assets/images/500x300.png" # 대체 티저 이미지 경로 예: "/assets/images/500x300.png"
logo                     : "/assets/images/android-chrome-96x96.png" # 마스트헤드에 표시할 로고 이미지 경로 예: "/assets/images/88x88.png"
masthead_title           : # 마스트헤드에 표시되는 웹사이트 제목을 재정의합니다. 제목을 없애려면 " " 사용
# breadcrumbs            : false # true, false (기본값)
words_per_minute         : 200
enable_copy_code_button  : # true, false (기본값)
copyright                : # "copyright" 이름, 기본값은 site.title
copyright_url            : # "copyright" URL, 기본값은 site.url
comments:
  provider               : # false (기본값), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , 예: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (기본값)
    colorscheme          : # "light" (기본값), "dark"
  utterances:
    theme                : # "github-light" (기본값), "github-dark"
    issue_term           : # "pathname" (기본값)
  giscus:
    repo_id              : # https://giscus.app에서 설정할 때 표시됨
    category_name        : # 카테고리의 전체 텍스트 이름
    category_id          : # https://giscus.app에서 설정할 때 표시됨
    discussion_term      : # "pathname" (기본값), "url", "title", "og:title"
    reactions_enabled    : # '1' 활성화 (기본값), '0' 비활성화
    theme                : # "light" (기본값), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    strict               : # 1 활성화, 0 비활성화 (기본값)
    input_position       : # "top", "bottom" # 댓글 입력 상자가 댓글 아래 또는 위에 배치됩니다.
    emit_metadata        : # 1 활성화, 0 비활성화 (기본값) # https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#imetadatamessage
    lang                 : # "en" (기본값)
    lazy                 : # true, false # 댓글 컨테이너 근처로 스크롤할 때까지 댓글 로딩이 지연됩니다.
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # 빈값 (기본값)은 feed.xml 사용
  hide                   : # true, false (기본값)
search                   : true # true, false (기본값)
search_full_content      : true # true, false (기본값)
search_provider          : lunr # lunr (기본값), algolia, google
lunr:
  search_within_pages    : false # true, false (기본값)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : true # true (기본값), false
  files_to_exclude:
   # - _posts/2017-11-28-post-exclude-search.md
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (기본값), true
# SEO 관련
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# 소셜 공유
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter 기본 사이트 이미지
# 소셜 프로필 지정
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person 또는 Organization (기본값은 Person)
  name                   : # 사용자 또는 조직 이름이 사이트 이름과 다를 경우
  links: # 소셜 미디어 프로필로 연결되는 링크 배열

# 분석
analytics:
  provider               : false # false (기본값), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (기본값)


# 사이트 작성자
author:
  name             : "Regular Expression"
  avatar           : "/assets/images/bio-photo.jpg" # 아바타 이미지 경로 예: "/assets/images/bio-photo.jpg"
  bio              : #"나는 **놀라운** 사람입니다."
  location         : "어딘가"
  email            :
  links:
    - label: "이메일"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "웹사이트"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "트위터"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "페이스북"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "인스타그램"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# 사이트 푸터
footer:
  links:
    - label: "트위터"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "페이스북"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "인스타그램"
      icon: "fab fa-fw fa-instagram"
      # url:


# 파일 읽기
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
#  - /docs # Minimal Mistakes /docs 무시
#  - /test # Minimal Mistakes /test 무시
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 변환
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown 처리
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# 출력
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# jekyll-paginate로 페이지네이션
paginate: 5 # 표시할 포스트 수
paginate_path: /page:num/

# jekyll-paginate-v2로 페이지네이션
# 설정 세부 정보는 https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration 참조
pagination:
  # paginate v2 사용하려면 enabled를 true로 설정
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2


# 플러그인 (이전에는 gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# --safe로 GitHub Pages 모방
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# 아카이브
#  유형
#  - Liquid로 빌드된 GitHub Pages 호환 아카이브 페이지 ~> type: liquid (기본값)
#  - Jekyll Archives 플러그인 아카이브 페이지 ~> type: jekyll-archives
#  경로 (예)
#  - Liquid 방법을 사용하는 경우 아카이브 페이지가 경로에 존재해야 하며, 그렇지 않으면 링크가 깨질 수 있습니다 (특히 breadcrumbs가 활성화된 경우).
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML 압축
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development



# 컬렉션
collections:
  sqlp:
    output: true
    permalink: /:collection/:path/
  dap:
    output: true
    permalink: /:collection/:path/
  docs:
    output: true
    permalink: /:collection/:path/

# 기본값
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _sqlp
  - scope:
      path: "_sqlp"
      type: sqlp
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_sticky: true
      sidebar:
        nav: "docs-sqlp"
  # _dap
  - scope:
      path: "_dap"
      type: dap
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_sticky: true
      sidebar:
        nav: "docs-dap"